### ISSUE TITLE
[BugFix] ErrorResponse 업그레이드 이후 발생한 버그 수정

### ISSUE THREAD

**Issue by hunzzzzz** [hunzzzzz/bingo-jango#49]
## 어떤 버그(에러)인가요?
ErrorResponse 업그레이드 이후 CustomAccessDeniedHandler, CustomAuthenticationEntryPoint 내부의 ErrorResponse 객체 생성 방식을 수정하지 않아 발생한 에러

## 작업 상세 내용
- [ ] CustomAccessDeniedHandler, CustomAuthenticationEntryPoint 내의 ErrorResponse 객체 생성 방식 수정

**Comment by WiGenie** [comment]
헉 이거 인증 관련 이슈에 굳이 경로랑 시간이 필요한가 싶어서 securityresponse 만들어서 거기다 이관했는데...
